### ISSUE TITLE
Blog module

### ISSUE THREAD

**Issue by esokullu** [phonetworks/graphjs#107]
I am to prepare to the server-side
Ozan to prepare the client-side:

```
<blog-composer ...>, 
<blog-post id=“…” with-title=“true”>
<blog-list titles-only=“true” max-count=“” order=“reverse-chronological|random”>
```

**Comment by ozanilbey** [comment]
**Client-side**

- General
- [ ] Add components to app.js
- [ ] Add calls to app.js
- [ ] Test components
- [ ] Test calls

- Components
- [ ] Create multifunctional wraper component named <blog>
- [ ] Create link and access to composer only if the user is admin (Multiadmin?)
- [ ] Create <blog-composer> component
- [ ] Add markdown editor as default
- [ ] Add other types of editors later (HTML?)
- [ ] Add preview option (Convert content to html while displaying?)
- [ ] Create <blog-list> component
- [ ] Create <blog-post> component with comments

**Comment by ozanilbey** [comment]
![screen shot 2018-11-08 at 7 24 50 pm](https://user-images.githubusercontent.com/3929181/48542420-2bc56b00-e8d0-11e8-88d9-98217f2cb89c.png)
