### ISSUE TITLE
blog-post displays unpublish and delete options even if the user is not logged

### ISSUE THREAD

**Issue by ozanilbey** [phonetworks/graphjs#133]
<img width="437" alt="screen shot 2018-12-08 at 10 58 50 pm" src="https://user-images.githubusercontent.com/3929181/49690145-fe6d8500-fb3c-11e8-972f-a61390d601c7.png">

I guess this got broken but it was working in the earlier version.

**Comment by ChaituVR** [comment]
PR merged .. we can close this
