### ISSUE TITLE
Profile Settings, change avatar z-index too low

### ISSUE THREAD

**Issue by esokullu** [phonetworks/graphjs#143]
To reproduce:

1. go to emresokullu.com
2. sign up with a new account
3. go to your profile >  settings > change avatar

Change avatar dialog won't appear.

It is actually hidden somewhere behind due to low z-index.

**Comment by ozanilbey** [comment]
Cannot go to my profile. How can I make it happen?

**Comment by ozanilbey** [comment]
Okay, I managed to reproduce it and fix it. Closing this issue.
