### ISSUE TITLE
Blog branding bug on single items

### ISSUE THREAD

**Issue by esokullu** [phonetworks/graphjs#146]
Brand and the Comments sections mix up.

<img width="683" alt="screen shot 2019-01-19 at 5 25 12 pm" src="https://user-images.githubusercontent.com/19166/51434183-9320d380-1c0f-11e9-97d4-06ed9cb0b3eb.png">

**Comment by esokullu** [comment]
Also, the blog composer should come collapsed by default. but even when it's uncollapsed, it shouldn't look this way.

**Comment by esokullu** [comment]
Same in overlay mode.

<img width="714" alt="screen shot 2019-01-19 at 5 34 26 pm" src="https://user-images.githubusercontent.com/19166/51434217-818bfb80-1c10-11e9-98ad-f51f4fc48219.png">

**Comment by ozanilbey** [comment]
> Also, the blog composer should come collapsed by default. but even when it's uncollapsed, it shouldn't look this way.

Did you mean **comment composer**? I'll change it if you want it collapsed by default.

**Comment by ozanilbey** [comment]
Fixed
