### ISSUE TITLE
Blog bugs continue....

### ISSUE THREAD

**Issue by esokullu** [phonetworks/graphjs#162]
To reproduce:

1. go to https://graphjs.com/docs/components/blog and click the first blog post, 
2. go to https://graphjs.com/docs/components/blog-list -- this is what I see:

![screen shot 2019-01-31 at 10 25 35 pm](https://user-images.githubusercontent.com/19166/52106317-27435100-25a7-11e9-961d-8ea826d5869e.png)

**Comment by ozanilbey** [comment]
Looks like i18n problem, @ChaituVR

**Comment by esokullu** [comment]
@ChaituVR can you confirm?

**Comment by ChaituVR** [comment]
It is working now, We can close this
