### ISSUE TITLE
Feed Composer Style Fix

### ISSUE THREAD

**Issue by esokullu** [phonetworks/graphjs#189]
To reproduce, take a look tests/index-feed.html

<img width="548" alt="Screen Shot 2019-03-25 at 4 17 23 PM" src="https://user-images.githubusercontent.com/19166/54922664-ac991100-4f19-11e9-927b-0204341213f9.png">

**Comment by ozanilbey** [comment]
Changed the icon. Renamed "File" as "Document" because it makes more sense. Also got rid of verbs. Will be active after the next commit.
