### ISSUE TITLE
In-Feed Style and Introduction of [title] tag

### ISSUE THREAD

**Issue by esokullu** [phonetworks/graphjs#190]
<img width="783" alt="Screen Shot 2019-03-25 at 4 22 30 PM" src="https://user-images.githubusercontent.com/19166/54927593-824c5100-4f23-11e9-8628-35484cc246b0.png">

https://gr.ps/palpitos

I believe we solved the \<br\> problem, now they are rendered as "pre" hence regular newlines are handled in the browser.

But the problem with the title continues. We should be able to put a title if we want to. So perhaps we should invent [title] which would render as \<h1\>

**Comment by ozanilbey** [comment]
Solved the title parsing problem. Will be active after the next commit.
