### ISSUE TITLE
Group Bug; invisible text

### ISSUE THREAD

**Issue by esokullu** [phonetworks/graphjs#202]
See below:
<img width="924" alt="Screen Shot 2019-04-21 at 5 14 50 PM" src="https://user-images.githubusercontent.com/19166/56477308-07f6ea00-6459-11e9-936f-8517aaa5e8dd.png">

The text "this group has no followers" is invisible.

**Comment by YaGen** [comment]
https://github.com/phonetworks/graphjs/pull/211
