### ISSUE TITLE
Can't see Help option in settings page

### ISSUE THREAD

**Issue by ChaituVR** [phonetworks/graphjs#228]
![image](https://user-images.githubusercontent.com/15967809/62832720-aa2d1e80-bc50-11e9-8eda-bd80f1fa3350.png)

**Comment by esokullu** [comment]
Good catch. But this one is probably a non-issue for now, because we will  remove Administration and move Members under Content Management with a new title.

**Comment by esokullu** [comment]
cc/ @YaGen

**Comment by YaGen** [comment]
Fixed with https://github.com/esokullu/graphjs-website/pull/164
