### ISSUE TITLE
In very large screens there's a padding problem

### ISSUE THREAD

**Issue by esokullu** [phonetworks/graphjs#36]
The latest widgets (after the content placeholder update) look great on MacBook, but there was a constant glitch of overflown body in the right-hand side on my Mac Pro.

You may want to test it on larger screen sizes. I don't have access to that computer now, so can't take a screenshot.

**Comment by esokullu** [comment]
What about this? Got a chance to look at this as well?

**Comment by ozanilbey** [comment]
Couldn't reproduce this either.

**Comment by esokullu** [comment]
I guess we should close this now.
