### ISSUE TITLE
Make color.less dynamically read and executed (instead of renderColor.js)

### ISSUE THREAD

**Issue by ozanilbey** [phonetworks/graphjs#67]

**Comment by esokullu** [comment]
can you elaborate?

**Comment by ozanilbey** [comment]
Less.render function takes a string containing Less conditionals. We have this string as and it works well for now. However, this is not a good practice. We have to evaluate a real Less file (in this case, it's color.less) and turn it into a string. This requires to read the file and Node fs module didn't help. Requiring the file won't help either. It automatically starts evaluating it as a Less file because of Webpack less-loader.
