### ISSUE TITLE
profile form update too hacky

### ISSUE THREAD

**Issue by esokullu** [phonetworks/graphjs#80]
![image](https://user-images.githubusercontent.com/19166/42381816-f282ea90-813a-11e8-8822-d6c2fb433560.png)

instead we should show an ok button in the right hand side of each input. 
the inputs should be updated individually (not all or nothing)

**Comment by ozanilbey** [comment]
Done! Will comment the commit hash later.

**Comment by ozanilbey** [comment]
[#6e3e2d8c56058819000b7f513e392617e57ded18](https://github.com/phonetworks/graphjs/commit/6e3e2d8c56058819000b7f513e392617e57ded18)
