### ISSUE TITLE
Auth State should be linked to the profile

### ISSUE THREAD

**Issue by ozanilbey** [phonetworks/graphjs#82]

**Comment by ozanilbey** [comment]
Done!

**Comment by esokullu** [comment]
commit #?

**Comment by ozanilbey** [comment]
Will comment the commit hash later.

**Comment by ozanilbey** [comment]
[#6e3e2d8c56058819000b7f513e392617e57ded18](https://github.com/phonetworks/graphjs/commit/6e3e2d8c56058819000b7f513e392617e57ded18)
