### ISSUE TITLE
Contact post-success-screen

### ISSUE THREAD

**Issue by esokullu** [phonetworks/graphjs#84]
![image](https://user-images.githubusercontent.com/19166/42509059-5e260c08-8453-11e8-82bf-81ccff0ce228.png)

There is no way to going back. There should be a timeout. In 4-5 secs it should go back, and/or there should be a button that lets people go back to the previous state.

**Comment by ozanilbey** [comment]
Done! Will comment the commit hash later.

**Comment by ozanilbey** [comment]
#6e3e2d8c56058819000b7f513e392617e57ded18
