### ISSUE TITLE
alternative to neo4j graph database?

### ISSUE THREAD

**Issue by rebootcode** [phonetworks/graphjs#98]
can we use other than neo4j graph database

**Comment by esokullu** [comment]
@rebootcode good point, we are investigating an alternative index layer on top of Redis. In case you'd like to contribute or do it on your own, check out https://github.com/pho-adapters and https://github.com/pho-adapters/index-neo4j

**Comment by rebootcode** [comment]
Is that's it for DB adapters - https://github.com/pho-adapters/database-redis/blob/master/Redis.php ?

If that is all, then I will send a create "dgraph based" soon!

Thanks
